### ISSUE TITLE
rna_stats.py not findable by script

### ISSUE THREAD

**Issue by wukevin** [Illumina/zippy#2]
Call to rna_stats.py cannot find the actual script, because execution never happens with the source dir as the current dir.

https://github.com/Illumina/zippy/blob/a60743c7fbf0b34d0cc98b35c9e8071d88ed49e3/zippy/modular_runner.py#L800

**Comment by aawise** [comment]
Fixed
https://github.com/Illumina/zippy/commit/446adb3febc1092467c7366f5e1b9c4649bff3cd

**Comment by quejebo** [comment]
Fixed

https://github.com/Illumina/zippy/commit/446adb3febc1092467c7366f5e1b9c4649bff3cd
